# ====================== This file is base file (all enviroments here use both Development and Production) ======================
version: "3"

services:
  node-app:
    build: .
    ports:
      - 3001:3001 # In this project, both dev. and prod. use same port. (If dev. and prod. not used same port, you should write port for docker-compose.dev.yaml and docker-compose.prod.yaml)
    environment:
      - PORT=3001
      - DB_URI=mongodb://admin:password@mongodb:27017
      - DB_NAME=docker-practice
    networks:
      - mongodb_network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27018:27017 # Connect with MongoDBCompass using "mongodb://admin:password@localhost:27018"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - practice-docker_mongodb:/data/db # persist data in db after ran command "docker-compose down"
    networks:
      - mongodb_network

volumes:
  practice-docker_mongodb:

networks:
  mongodb_network:
    name: mongodb-network
